default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: label_notifier_development

test:
  <<: *default
  database: label_notifier_test

production:
  <<: *default
  database: label_notifier_production
  username: webapp
